/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    AppPagination: typeof import('./components/layout/AppPagination.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    CheckpointDetailModal: typeof import('./components/common/CheckpointDetailModal.vue')['default']
    CheckpointUpdateModal: typeof import('./components/common/CheckpointUpdateModal.vue')['default']
    DailyUpdateCard: typeof import('./components/common/DailyUpdateCard.vue')['default']
    DailyUpdateFeed: typeof import('./components/common/DailyUpdateFeed.vue')['default']
    DailyUpdateModal: typeof import('./components/common/DailyUpdateModal.vue')['default']
    ExpenseDetailModal: typeof import('./components/common/ExpenseDetailModal.vue')['default']
    ExpenseRequestModal: typeof import('./components/common/ExpenseRequestModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PhaseCard: typeof import('./components/common/PhaseCard.vue')['default']
    ProjectCard: typeof import('./components/common/ProjectCard.vue')['default']
    ProjectDetailCard: typeof import('./components/common/ProjectDetailCard.vue')['default']
    ProjectDocumentsTab: typeof import('./components/common/ProjectDocumentsTab.vue')['default']
    ProjectFormModal: typeof import('./components/common/ProjectFormModal.vue')['default']
    ProjectList: typeof import('./components/common/ProjectList.vue')['default']
    ProjectOverviewTab: typeof import('./components/common/ProjectOverviewTab.vue')['default']
    ProjectPhaseEditor: typeof import('./components/common/ProjectPhaseEditor.vue')['default']
    ProjectPhotoLightbox: typeof import('./components/common/ProjectPhotoLightbox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./components/common/StatsCard.vue')['default']
    TemplateCard: typeof import('./components/common/TemplateCard.vue')['default']
    TemplateFormModal: typeof import('./components/common/TemplateFormModal.vue')['default']
    TemplatePhaseEditor: typeof import('./components/common/TemplatePhaseEditor.vue')['default']
    TemplateViewModal: typeof import('./components/common/TemplateViewModal.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
    UserFormModal: typeof import('./components/common/UserFormModal.vue')['default']
    UserRoleTag: typeof import('./components/common/UserRoleTag.vue')['default']
    UserTableRow: typeof import('./components/common/UserTableRow.vue')['default']
  }
}
