/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    AppPagination: typeof import('./components/layout/AppPagination.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ProjectCard: typeof import('./components/common/ProjectCard.vue')['default']
    ProjectList: typeof import('./components/common/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./components/common/StatsCard.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
    UserFormModal: typeof import('./components/common/UserFormModal.vue')['default']
    UserRoleTag: typeof import('./components/common/UserRoleTag.vue')['default']
    UserTableRow: typeof import('./components/common/UserTableRow.vue')['default']
  }
}
